//! meshopt binary compat verification against C++ reference vectors
//!
//! Reference `.bin` files were generated by running the meshoptimizer v0.24 C++
//! library (see `/tmp/meshopt-ref/gen_vectors.cpp`) and stored in
//! `tests/meshopt_vectors/`.
//!
//! Each fixture has 3 files:
//! - `<name>_indices.bin` or `<name>_vertices.bin`: meshopt-encoded bytes
//! - `<name>_indices_raw.bin` or `<name>_vertices_raw.bin`: original bytes
//! - `<name>_indices_meta.bin`: 4 bytes little-endian u32 (index count)
//! - `<name>_vertices_meta.bin`: 8 bytes (u32 vertex_count, u32 vertex_size)

use alice_sdf::mesh::meshopt_index_codec::decode_index_buffer;
use alice_sdf::mesh::meshopt_vertex_codec::decode_vertex_buffer;
use std::fs;
use std::path::Path;

const VECTORS_DIR: &str = "tests/meshopt_vectors";

fn read_bin(path: &Path) -> Vec<u8> {
    fs::read(path).unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()))
}

fn read_index_meta(name: &str) -> u32 {
    let path = Path::new(VECTORS_DIR).join(format!("{name}_indices_meta.bin"));
    let bytes = read_bin(&path);
    assert_eq!(bytes.len(), 4);
    u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]])
}

fn read_vertex_meta(name: &str) -> (u32, u32) {
    let path = Path::new(VECTORS_DIR).join(format!("{name}_vertices_meta.bin"));
    let bytes = read_bin(&path);
    assert_eq!(bytes.len(), 8);
    let count = u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);
    let size = u32::from_le_bytes([bytes[4], bytes[5], bytes[6], bytes[7]]);
    (count, size)
}

fn triangles_equivalent(input: &[u32], decoded: &[u32]) -> bool {
    if input.len() != decoded.len() {
        return false;
    }
    for t in 0..(input.len() / 3) {
        let base = t * 3;
        let a = input[base];
        let b = input[base + 1];
        let c = input[base + 2];
        let da = decoded[base];
        let db = decoded[base + 1];
        let dc = decoded[base + 2];
        let rot0 = da == a && db == b && dc == c;
        let rot1 = da == b && db == c && dc == a;
        let rot2 = da == c && db == a && dc == b;
        if !(rot0 || rot1 || rot2) {
            return false;
        }
    }
    true
}

fn verify_indices(name: &str) {
    let encoded = read_bin(&Path::new(VECTORS_DIR).join(format!("{name}_indices.bin")));
    let raw_bytes = read_bin(&Path::new(VECTORS_DIR).join(format!("{name}_indices_raw.bin")));
    let count = read_index_meta(name) as usize;

    assert_eq!(
        raw_bytes.len(),
        count * 4,
        "{name}: raw byte size {} != count {} * 4",
        raw_bytes.len(),
        count
    );
    let expected: Vec<u32> = raw_bytes
        .chunks_exact(4)
        .map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();

    let decoded = decode_index_buffer(&encoded, count)
        .unwrap_or_else(|e| panic!("{name}: decode failed: {e:?}"));

    assert_eq!(
        decoded.len(),
        expected.len(),
        "{name}: decoded count mismatch"
    );
    assert!(
        triangles_equivalent(&expected, &decoded),
        "{name}: topological mismatch\n  input:   {:?}\n  decoded: {:?}",
        &expected[..expected.len().min(20)],
        &decoded[..decoded.len().min(20)],
    );

    eprintln!(
        "  {name}: {} indices, encoded {} bytes → decoded OK (topological)",
        count,
        encoded.len()
    );
}

fn verify_vertices(name: &str) {
    let encoded = read_bin(&Path::new(VECTORS_DIR).join(format!("{name}_vertices.bin")));
    let raw_bytes = read_bin(&Path::new(VECTORS_DIR).join(format!("{name}_vertices_raw.bin")));
    let (count, size) = read_vertex_meta(name);
    let count = count as usize;
    let size = size as usize;

    assert_eq!(
        raw_bytes.len(),
        count * size,
        "{name}: raw byte size mismatch"
    );

    let decoded = decode_vertex_buffer(&encoded, count, size)
        .unwrap_or_else(|e| panic!("{name}: decode failed: {e:?}"));

    assert_eq!(
        decoded, raw_bytes,
        "{name}: vertex decode bit-exact mismatch"
    );

    eprintln!(
        "  {name}: {} verts × {} bytes = {} bytes, encoded {} bytes → decoded bit-exact OK",
        count,
        size,
        raw_bytes.len(),
        encoded.len()
    );
}

// --- Index buffer reference vector tests ---

#[test]
fn ref_index_tri_single() {
    verify_indices("tri_single");
}

#[test]
fn ref_index_strip_small() {
    verify_indices("strip_small");
}

#[test]
fn ref_index_seq_100() {
    verify_indices("seq_100");
}

// --- Vertex buffer reference vector tests ---

#[test]
fn ref_vertex_tri_single() {
    verify_vertices("tri_single");
}

#[test]
fn ref_vertex_strip_small() {
    verify_vertices("strip_small");
}

#[test]
fn ref_vertex_seq_100() {
    verify_vertices("seq_100");
}

#[test]
fn ref_vertex_large_500() {
    verify_vertices("large_500");
}

#[test]
fn ref_vertex_uniform() {
    verify_vertices("uniform");
}
