// ALICE-SDF UE5 Plugin — corpus oracle automation tests
// Author: Moroya Sakamoto
//
// The plugin reaches alice-sdf through the C FFI (alice_sdf.dll) and the
// HLSL transpiler. These two tests are the only place either is checked
// *inside Unreal*:
//
//   AliceSDF.Unreal.FfiCorpusParity
//     Every corpus node (tests/common/corpus.rs, 145 laws) is loaded from
//     the .asdf the Rust side wrote, evaluated through alice_sdf_eval /
//     alice_sdf_eval_compiled / alice_sdf_eval_compiled_batch on the
//     test_det_golden grid, and compared bit for bit with the tree
//     evaluator's recorded answer. A mismatch means the DLL the plugin
//     links is not the crate (stale binary, ABI drift, broken .asdf codec)
//     — the state the repo was in from 1.7.2 to 3.1.0.
//
//   AliceSDF.Unreal.HlslGpuOracle
//     Every shader-capable corpus node's transpiled HLSL runs as a compute
//     shader on the editor's real RHI (DX12 on the CI runner) and is
//     compared with the DLL at 1e-4 · max(|d|, 1), the tolerance of
//     tests/test_gpu_law_parity.rs. This is the crate's only HLSL
//     *execution* oracle: naga has no HLSL front end, so the wgpu lanes
//     cover WGSL and GLSL and the Windows lane only FXC-compiles HLSL.
//
// Inputs (generated by `cargo run --example unreal_corpus_oracle`):
//   ALICE_SDF_GOLDEN_DIR      .asdf + .golden + points.txt (not committed;
//                             default <ProjectSavedDir>/AliceSdfGolden)
//   ALICE_SDF_CORPUS_ORACLE=1 include the corpus permutations of
//                             FAliceSdfCorpusOracleCS in the global shader
//                             map (145 compute shaders; off by default so a
//                             user's editor does not pay for them)
//   ALICE_SDF_REQUIRE_GOLDEN=1 / ALICE_SDF_REQUIRE_GPU=1
//                             turn "inputs missing → warn + skip" into a
//                             failure (CI sets both; mirrors the crate's
//                             ALICE_SDF_REQUIRE_GPU convention)

#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS

#include "alice_sdf.h"
#include "Generated/AliceSdfCorpusManifest.h"

#include "GlobalShader.h"
#include "ShaderParameterStruct.h"
#include "RenderGraphBuilder.h"
#include "RenderGraphUtils.h"
#include "RHIGPUReadback.h"
#include "RenderingThread.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "HAL/PlatformMisc.h"
#include "Containers/StringConv.h"

// ============================================================================
// Shared helpers
// ============================================================================

namespace AliceSdfOracle
{
	static FString GoldenDir()
	{
		FString Dir = FPlatformMisc::GetEnvironmentVariable(TEXT("ALICE_SDF_GOLDEN_DIR"));
		if (Dir.IsEmpty())
		{
			Dir = FPaths::ProjectSavedDir() / TEXT("AliceSdfGolden");
		}
		return Dir;
	}

	static bool EnvFlag(const TCHAR* Name)
	{
		return FPlatformMisc::GetEnvironmentVariable(Name) == TEXT("1");
	}

	/// points.txt: one `xbits ybits zbits` (hex u32) per line, in the order
	/// examples/unreal_corpus_oracle.rs::grid produced them.
	static bool LoadPoints(const FString& Dir, TArray<FVector3f>& OutPoints, FString& OutError)
	{
		TArray<FString> Lines;
		const FString Path = Dir / TEXT("points.txt");
		if (!FFileHelper::LoadFileToStringArray(Lines, *Path))
		{
			OutError = FString::Printf(TEXT("cannot read %s"), *Path);
			return false;
		}
		OutPoints.Reset(Lines.Num());
		for (const FString& Line : Lines)
		{
			if (Line.IsEmpty())
			{
				continue;
			}
			TArray<FString> Parts;
			Line.ParseIntoArrayWS(Parts);
			if (Parts.Num() != 3)
			{
				OutError = FString::Printf(TEXT("%s: bad line `%s`"), *Path, *Line);
				return false;
			}
			uint32 Bits[3];
			for (int32 i = 0; i < 3; i++)
			{
				Bits[i] = FParse::HexNumber(*Parts[i]);
			}
			float F[3];
			FMemory::Memcpy(F, Bits, sizeof(F));
			OutPoints.Add(FVector3f(F[0], F[1], F[2]));
		}
		if (OutPoints.Num() != ALICE_SDF_CORPUS_GRID_POINTS)
		{
			OutError = FString::Printf(TEXT("%s: %d points, manifest says %d — regenerate both"),
				*Path, OutPoints.Num(), ALICE_SDF_CORPUS_GRID_POINTS);
			return false;
		}
		return true;
	}

	/// <name>.golden: one hex u32 (f32 bits of the tree evaluator) per point.
	static bool LoadGolden(const FString& Dir, const TCHAR* Name, int32 NumPoints, TArray<uint32>& OutBits, FString& OutError)
	{
		TArray<FString> Lines;
		const FString Path = Dir / FString::Printf(TEXT("%s.golden"), Name);
		if (!FFileHelper::LoadFileToStringArray(Lines, *Path))
		{
			OutError = FString::Printf(TEXT("cannot read %s"), *Path);
			return false;
		}
		OutBits.Reset(NumPoints);
		for (const FString& Line : Lines)
		{
			if (!Line.IsEmpty())
			{
				OutBits.Add(FParse::HexNumber(*Line));
			}
		}
		if (OutBits.Num() != NumPoints)
		{
			OutError = FString::Printf(TEXT("%s: %d values for %d points"), *Path, OutBits.Num(), NumPoints);
			return false;
		}
		return true;
	}

	static uint32 Bits(float F)
	{
		uint32 B;
		FMemory::Memcpy(&B, &F, sizeof(B));
		return B;
	}

	static SdfHandle LoadNode(const FString& Dir, const TCHAR* Name)
	{
		const FString Path = Dir / FString::Printf(TEXT("%s.asdf"), Name);
		return alice_sdf_load(TCHAR_TO_UTF8(*Path));
	}
}

// ============================================================================
// AliceSDF.Unreal.FfiCorpusParity
// ============================================================================

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAliceSdfFfiCorpusParityTest,
	"AliceSDF.Unreal.FfiCorpusParity",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ClientContext | EAutomationTestFlags::ProductFilter)

bool FAliceSdfFfiCorpusParityTest::RunTest(const FString& Parameters)
{
	using namespace AliceSdfOracle;

	const FString Dir = GoldenDir();
	TArray<FVector3f> Points;
	FString Error;
	if (!LoadPoints(Dir, Points, Error))
	{
		if (EnvFlag(TEXT("ALICE_SDF_REQUIRE_GOLDEN")))
		{
			AddError(FString::Printf(TEXT("ALICE_SDF_REQUIRE_GOLDEN is set but: %s"), *Error));
			return false;
		}
		AddWarning(FString::Printf(TEXT("skipped — %s (run `cargo run --example unreal_corpus_oracle` and set ALICE_SDF_GOLDEN_DIR)"), *Error));
		return true;
	}

	const VersionInfo Version = alice_sdf_version();
	AddInfo(FString::Printf(TEXT("alice_sdf.dll %u.%u.%u, %d corpus nodes, %d points"),
		Version.major, Version.minor, Version.patch, ALICE_SDF_CORPUS_COUNT, Points.Num()));

	int32 NodesChecked = 0;
	for (int32 NodeIdx = 0; NodeIdx < ALICE_SDF_CORPUS_COUNT; NodeIdx++)
	{
		const TCHAR* Name = GAliceSdfCorpusNames[NodeIdx];

		TArray<uint32> Golden;
		if (!LoadGolden(Dir, Name, Points.Num(), Golden, Error))
		{
			AddError(Error);
			continue;
		}

		SdfHandle Node = LoadNode(Dir, Name);
		if (!Node)
		{
			AddError(FString::Printf(TEXT("%s: alice_sdf_load returned null"), Name));
			continue;
		}
		// A handful of corpus nodes have no bytecode form (`terrain` carries a
		// heightmap the VM has no opcode for). The generator records which,
		// so this is a two-way check: compilable nodes must compile, and the
		// others must keep failing rather than start silently succeeding.
		const bool bExpectCompilable = GAliceSdfCorpusCompilable[NodeIdx];
		CompiledHandle Compiled = alice_sdf_compile(Node);
		if (!bExpectCompilable)
		{
			if (Compiled)
			{
				AddError(FString::Printf(
					TEXT("%s: alice_sdf_compile succeeded, but CompiledSdf::try_compile rejects it — regenerate the manifest"),
					Name));
				alice_sdf_free_compiled(Compiled);
			}
			// Still hold the tree evaluator to the golden bits.
			int32 TreeOnlyMismatch = 0;
			for (int32 i = 0; i < Points.Num(); i++)
			{
				const FVector3f& P = Points[i];
				if (Bits(alice_sdf_eval(Node, P.X, P.Y, P.Z)) != Golden[i])
				{
					TreeOnlyMismatch++;
				}
			}
			if (TreeOnlyMismatch > 0)
			{
				AddError(FString::Printf(TEXT("%s (tree only): %d of %d points differ from the Rust golden"),
					Name, TreeOnlyMismatch, Points.Num()));
			}
			NodesChecked++;
			alice_sdf_free(Node);
			continue;
		}
		if (!Compiled)
		{
			AddError(FString::Printf(TEXT("%s: alice_sdf_compile returned null"), Name));
			alice_sdf_free(Node);
			continue;
		}

		// Batch path (what UAliceSdfComponent::EvalDistanceBatch uses).
		TArray<float> Flat;
		Flat.SetNum(Points.Num() * 3);
		for (int32 i = 0; i < Points.Num(); i++)
		{
			Flat[i * 3 + 0] = Points[i].X;
			Flat[i * 3 + 1] = Points[i].Y;
			Flat[i * 3 + 2] = Points[i].Z;
		}
		TArray<float> Batch;
		Batch.SetNum(Points.Num());
		const BatchResult BatchRes = alice_sdf_eval_compiled_batch(Compiled, Flat.GetData(), Batch.GetData(), Points.Num());
		if (BatchRes.result != SdfResult_Ok || BatchRes.count != static_cast<uint32>(Points.Num()))
		{
			AddError(FString::Printf(TEXT("%s: alice_sdf_eval_compiled_batch result=%d count=%u"), Name, static_cast<int32>(BatchRes.result), BatchRes.count));
		}

		int32 TreeMismatch = 0, CompiledMismatch = 0, BatchMismatch = 0;
		FString First;
		for (int32 i = 0; i < Points.Num(); i++)
		{
			const FVector3f& P = Points[i];
			const uint32 Tree = Bits(alice_sdf_eval(Node, P.X, P.Y, P.Z));
			const uint32 Comp = Bits(alice_sdf_eval_compiled(Compiled, P.X, P.Y, P.Z));
			const uint32 Bat = Bits(Batch[i]);
			if (Tree != Golden[i])
			{
				if (TreeMismatch++ == 0)
				{
					First = FString::Printf(TEXT("tree @(%g,%g,%g) got %08x want %08x"), P.X, P.Y, P.Z, Tree, Golden[i]);
				}
			}
			if (Comp != Golden[i])
			{
				if (CompiledMismatch++ == 0 && First.IsEmpty())
				{
					First = FString::Printf(TEXT("compiled @(%g,%g,%g) got %08x want %08x"), P.X, P.Y, P.Z, Comp, Golden[i]);
				}
			}
			if (Bat != Golden[i])
			{
				if (BatchMismatch++ == 0 && First.IsEmpty())
				{
					First = FString::Printf(TEXT("batch @(%g,%g,%g) got %08x want %08x"), P.X, P.Y, P.Z, Bat, Golden[i]);
				}
			}
		}
		if (TreeMismatch + CompiledMismatch + BatchMismatch > 0)
		{
			AddError(FString::Printf(TEXT("%s: bit mismatch vs Rust golden — tree %d, compiled %d, batch %d of %d points; first: %s"),
				Name, TreeMismatch, CompiledMismatch, BatchMismatch, Points.Num(), *First));
		}
		NodesChecked++;

		alice_sdf_free_compiled(Compiled);
		alice_sdf_free(Node);
	}

	AddInfo(FString::Printf(TEXT("FFI corpus parity: %d / %d nodes bit-exact through alice_sdf.dll"), NodesChecked, ALICE_SDF_CORPUS_COUNT));
	TestEqual(TEXT("every corpus node was checked"), NodesChecked, ALICE_SDF_CORPUS_COUNT);
	return true;
}

// ============================================================================
// AliceSDF.Unreal.HlslGpuOracle
// ============================================================================

class FAliceSdfCorpusOracleCS : public FGlobalShader
{
	DECLARE_GLOBAL_SHADER(FAliceSdfCorpusOracleCS);
	SHADER_USE_PARAMETER_STRUCT(FAliceSdfCorpusOracleCS, FGlobalShader);

	class FNodeDim : SHADER_PERMUTATION_INT("ALICE_CORPUS_NODE", ALICE_SDF_CORPUS_SHADER_COUNT);
	using FPermutationDomain = TShaderPermutationDomain<FNodeDim>;

	BEGIN_SHADER_PARAMETER_STRUCT(FParameters, )
		SHADER_PARAMETER_RDG_BUFFER_SRV(StructuredBuffer<float4>, Points)
		SHADER_PARAMETER_RDG_BUFFER_UAV(RWStructuredBuffer<float>, Distances)
		SHADER_PARAMETER(uint32, PointCount)
	END_SHADER_PARAMETER_STRUCT()

	static constexpr uint32 ThreadGroupSize = 64;

	static bool ShouldCompilePermutation(const FGlobalShaderPermutationParameters& Parameters)
	{
		// 145 compute shaders nobody but the oracle test dispatches: only
		// put them in the global shader map when the environment asks.
		static const bool bEnabled = FPlatformMisc::GetEnvironmentVariable(TEXT("ALICE_SDF_CORPUS_ORACLE")) == TEXT("1");
		return bEnabled && IsFeatureLevelSupported(Parameters.Platform, ERHIFeatureLevel::SM5);
	}
};

IMPLEMENT_GLOBAL_SHADER(FAliceSdfCorpusOracleCS,
	"/Plugin/AliceSDF/CorpusOracle/SdfCorpusOracle.usf", "MainCS", SF_Compute);

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FAliceSdfHlslGpuOracleTest,
	"AliceSDF.Unreal.HlslGpuOracle",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ClientContext | EAutomationTestFlags::ProductFilter | EAutomationTestFlags::NonNullRHI)

bool FAliceSdfHlslGpuOracleTest::RunTest(const FString& Parameters)
{
	using namespace AliceSdfOracle;

	const bool bRequireGpu = EnvFlag(TEXT("ALICE_SDF_REQUIRE_GPU"));
	if (!EnvFlag(TEXT("ALICE_SDF_CORPUS_ORACLE")))
	{
		const FString Msg = TEXT("ALICE_SDF_CORPUS_ORACLE=1 was not set when the editor started, so the corpus permutations are not in the shader map");
		if (bRequireGpu)
		{
			AddError(Msg);
			return false;
		}
		AddWarning(TEXT("skipped — ") + Msg);
		return true;
	}
	if (bRequireGpu && (GDynamicRHI == nullptr || !(IsRHIDeviceNVIDIA() || IsRHIDeviceAMD() || IsRHIDeviceIntel())))
	{
		// A software / null RHI would still run, but the oracle is about a
		// real device; CI asks for one explicitly.
		AddError(TEXT("ALICE_SDF_REQUIRE_GPU is set but no hardware RHI device is active"));
		return false;
	}

	const FString Dir = GoldenDir();
	TArray<FVector3f> GridPoints;
	FString Error;
	if (!LoadPoints(Dir, GridPoints, Error))
	{
		if (EnvFlag(TEXT("ALICE_SDF_REQUIRE_GOLDEN")))
		{
			AddError(FString::Printf(TEXT("ALICE_SDF_REQUIRE_GOLDEN is set but: %s"), *Error));
			return false;
		}
		AddWarning(FString::Printf(TEXT("skipped — %s"), *Error));
		return true;
	}

	// Random points only (the appended ties are platform-dependent on GPUs,
	// see test_gpu_law_parity.rs).
	const int32 NumPoints = ALICE_SDF_CORPUS_RANDOM_POINTS;
	TArray<FVector4f> Points;
	Points.Reserve(NumPoints);
	for (int32 i = 0; i < NumPoints; i++)
	{
		Points.Add(FVector4f(GridPoints[i].X, GridPoints[i].Y, GridPoints[i].Z, 0.0f));
	}

	AddInfo(FString::Printf(TEXT("RHI %s, %d shader-capable corpus nodes, %d points"),
		GDynamicRHI ? GDynamicRHI->GetName() : TEXT("null"), ALICE_SDF_CORPUS_SHADER_COUNT, NumPoints));

	int32 NodesChecked = 0;
	for (int32 NodeIdx = 0; NodeIdx < ALICE_SDF_CORPUS_SHADER_COUNT; NodeIdx++)
	{
		const TCHAR* Name = GAliceSdfCorpusShaderNames[NodeIdx];

		SdfHandle Node = LoadNode(Dir, Name);
		if (!Node)
		{
			AddError(FString::Printf(TEXT("%s: alice_sdf_load returned null"), Name));
			continue;
		}

		// --- GPU ---
		TArray<float> Gpu;
		Gpu.SetNumZeroed(NumPoints);
		bool bDispatched = false;
		ENQUEUE_RENDER_COMMAND(AliceSdfCorpusOracle)(
			[NodeIdx, &Points, &Gpu, &bDispatched, NumPoints](FRHICommandListImmediate& RHICmdList)
		{
			FAliceSdfCorpusOracleCS::FPermutationDomain Permutation;
			Permutation.Set<FAliceSdfCorpusOracleCS::FNodeDim>(NodeIdx);
			TShaderMapRef<FAliceSdfCorpusOracleCS> Shader(GetGlobalShaderMap(GMaxRHIFeatureLevel), Permutation);
			if (!Shader.IsValid())
			{
				return;
			}

			FRDGBuilder GraphBuilder(RHICmdList);
			FRDGBufferRef PointsBuffer = CreateStructuredBuffer(GraphBuilder, TEXT("AliceSdfOracle.Points"), Points);
			FRDGBufferRef OutBuffer = GraphBuilder.CreateBuffer(
				FRDGBufferDesc::CreateStructuredDesc(sizeof(float), NumPoints), TEXT("AliceSdfOracle.Distances"));

			FAliceSdfCorpusOracleCS::FParameters* Params = GraphBuilder.AllocParameters<FAliceSdfCorpusOracleCS::FParameters>();
			Params->Points = GraphBuilder.CreateSRV(PointsBuffer);
			Params->Distances = GraphBuilder.CreateUAV(OutBuffer);
			Params->PointCount = NumPoints;

			FComputeShaderUtils::AddPass(GraphBuilder, RDG_EVENT_NAME("AliceSdfCorpusOracle(%d)", NodeIdx), Shader, Params,
				FComputeShaderUtils::GetGroupCount(NumPoints, FAliceSdfCorpusOracleCS::ThreadGroupSize));

			FRHIGPUBufferReadback Readback(TEXT("AliceSdfOracle.Readback"));
			AddEnqueueCopyPass(GraphBuilder, &Readback, OutBuffer, NumPoints * sizeof(float));
			GraphBuilder.Execute();

			RHICmdList.BlockUntilGPUIdle();
			const void* Data = Readback.Lock(NumPoints * sizeof(float));
			if (Data)
			{
				FMemory::Memcpy(Gpu.GetData(), Data, NumPoints * sizeof(float));
				bDispatched = true;
			}
			Readback.Unlock();
		});
		FlushRenderingCommands();

		if (!bDispatched)
		{
			AddError(FString::Printf(TEXT("%s: permutation %d is not in the global shader map or the readback failed"), Name, NodeIdx));
			alice_sdf_free(Node);
			continue;
		}

		// --- CPU (the DLL) at the same tolerance as test_gpu_law_parity ---
		float Worst = 0.0f;
		int32 WorstIdx = -1;
		for (int32 i = 0; i < NumPoints; i++)
		{
			const FVector4f& P = Points[i];
			const float C = alice_sdf_eval(Node, P.X, P.Y, P.Z);
			const float Tol = 1e-4f * FMath::Max(FMath::Abs(C), 1.0f);
			const float Diff = FMath::Abs(Gpu[i] - C);
			if (Diff > Tol && Diff > Worst)
			{
				Worst = Diff;
				WorstIdx = i;
			}
		}
		if (WorstIdx >= 0)
		{
			const FVector4f& P = Points[WorstIdx];
			AddError(FString::Printf(TEXT("%s: HLSL/CPU drift %.3e @(%g,%g,%g) gpu %g cpu %g"),
				Name, Worst, P.X, P.Y, P.Z, Gpu[WorstIdx], alice_sdf_eval(Node, P.X, P.Y, P.Z)));
		}
		NodesChecked++;
		alice_sdf_free(Node);
	}

	AddInfo(FString::Printf(TEXT("HLSL GPU oracle: %d / %d corpus nodes within 1e-4·max(|d|,1)"), NodesChecked, ALICE_SDF_CORPUS_SHADER_COUNT));
	TestEqual(TEXT("every shader-capable corpus node was dispatched"), NodesChecked, ALICE_SDF_CORPUS_SHADER_COUNT);
	return true;
}

#endif // WITH_DEV_AUTOMATION_TESTS
