// swift-tools-version: 5.9
// ALICE-SDF Mobile — SwiftPM Package
//
// Usage:
//   .package(path: "../ALICE-SDF/mobile/swift-package")
//   targets: [.executableTarget(name: "MyApp", dependencies: ["AliceSDF"])]

import PackageDescription

let package = Package(
    name: "AliceSDF",
    platforms: [
        .iOS(.v17),
        .macOS(.v13),
    ],
    products: [
        .library(name: "AliceSDF", targets: ["AliceSDF"]),
    ],
    targets: [
        // 1. Pre-built static framework (Rust core + C-ABI + UniFFI scaffolding)
        .binaryTarget(
            name: "AliceSDFFramework",
            path: "../uniffi-wrapper/target/xcframework/AliceSDF.xcframework"
        ),

        // 2. Swift bindings layer (alice_sdf.swift generated by UniFFI)
        //    This depends on the binary framework for the underlying C ABI.
        .target(
            name: "AliceSDF",
            dependencies: ["AliceSDFFramework"],
            path: "Sources/AliceSDF"
        ),
    ]
)
